
name: money_mind
description: Personal Finance Management App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  intl: ^0.18.0
  fl_chart: ^0.63.0
  
  # Firebase packages
  firebase_core: ^2.24.2
  cloud_firestore: ^4.15.2
  firebase_analytics: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
